insert into enderecos (cidade, principal, estado, rua, cep) values ('Albuquerque', true, 'NM', 'Boyd', 1),
  ('Fresno', true, 'CA', 'Lakewood Gardens', 2),
  ('Austin', false, 'TX', 'Anderson', 3),
  ('High Point', true, 'NC', 'Upham', 4),
  ('Fresno', false, 'CA', 'Surrey', 5),
  ('Durham', false, 'NC', 'Everett', 6),
  ('Fort Wayne', false, 'IN', 'Mcbride', 7),
  ('Palatine', false, 'IL', 'Arrowood', 8),
  ('San Antonio', true, 'TX', 'Cambridge', 9),
  ('San Francisco', false, 'CA', 'Mandrake', 10),
  ('London', false, 'KY', 'Tomscot', 11),
  ('Fort Lauderdale', false, 'FL', 'Emmet', 12),
  ('Spokane', true, 'WA', 'Linden', 13),
  ('Vancouver', true, 'WA', 'Havey', 14),
  ('Peoria', false, 'IL', 'Boyd', 15),
  ('Pittsburgh', false, 'PA', 'Larry', 16),
  ('Rochester', false, 'NY', 'Hudson', 17),
  ('Portland', true, 'OR', 'Cascade', 18),
  ('Laredo', false, 'TX', 'Coleman', 19),
  ('New Orleans', false, 'LA', 'Pennsylvania', 20),
  ('Fort Wayne', false, 'IN', 'Oriole', 21),
  ('Saint Louis', true, 'MO', 'Eastlawn', 22),
  ('Tucson', false, 'AZ', 'Bluejay', 23),
  ('Vancouver', true, 'WA', 'Lyons', 24),
  ('Roanoke', false, 'VA', 'Bonner', 25),
  ('Pittsburgh', true, 'PA', 'Bluestem', 26),
  ('Terre Haute', true, 'IN', 'Loeprich', 27),
  ('New York City', true, 'NY', 'Summer Ridge', 28),
  ('Buffalo', true, 'NY', 'Waxwing', 29),
  ('Springfield', false, 'IL', 'Hermina', 30),
  ('El Paso', true, 'TX', 'Becker', 31),
  ('Colorado Springs', true, 'CO', 'Magdeline', 32),
  ('Omaha', false, 'NE', 'Delaware', 33),
  ('Cedar Rapids', true, 'IA', 'Merrick', 34),
  ('Midland', false, 'MI', 'Tennyson', 35),
  ('New York City', true, 'NY', 'Gina', 36),
  ('Indianapolis', false, 'IN', 'Oxford', 37),
  ('Evansville', false, 'IN', 'Merry', 38),
  ('Louisville', false, 'KY', 'Thackeray', 39),
  ('Huntington', false, 'WV', 'Parkside', 40),
  ('Los Angeles', false, 'CA', 'Stephen', 41),
  ('Evansville', true, 'IN', '2nd', 42),
  ('Oakland', true, 'CA', 'Forest Run', 43),
  ('Oklahoma City', true, 'OK', 'West', 44),
  ('Des Moines', false, 'IA', 'Bobwhite', 45),
  ('Peoria', true, 'AZ', 'Warner', 46),
  ('Panama City', false, 'FL', 'Morrow', 47),
  ('Columbia', true, 'SC', 'Dryden', 48),
  ('New York City', false, 'NY', 'Waubesa', 49),
  ('Pensacola', true, 'FL', 'Dennis', 50),
  ('Shreveport', true, 'LA', 'Buhler', 51),
  ('Lexington', false, 'KY', 'Butterfield', 52),
  ('Saint Joseph', false, 'MO', 'Ramsey', 53),
  ('Washington', false, 'DC', 'Roxbury', 54),
  ('Alexandria', true, 'VA', 'Crownhardt', 55),
  ('Odessa', false, 'TX', 'Dorton', 56),
  ('Washington', true, 'DC', 'Cordelia', 57),
  ('Houston', true, 'TX', 'Forest Run', 58),
  ('Washington', true, 'DC', 'Harper', 59),
  ('Boston', true, 'MA', 'Norway Maple', 60),
  ('Jamaica', false, 'NY', 'Debra', 61),
  ('Brea', true, 'CA', 'Moose', 62),
  ('Dallas', false, 'TX', 'Service', 63),
  ('Little Rock', false, 'AR', 'Helena', 64),
  ('Springfield', true, 'IL', 'Mallard', 65),
  ('Reno', false, 'NV', 'Clarendon', 66),
  ('Baltimore', true, 'MD', 'Talisman', 67),
  ('Fresno', false, 'CA', 'Kipling', 68),
  ('Washington', false, 'DC', 'Mockingbird', 69),
  ('Washington', false, 'DC', 'Elgar', 70),
  ('San Bernardino', true, 'CA', 'Dottie', 71),
  ('Vero Beach', true, 'FL', 'Golf Course', 72),
  ('Dayton', true, 'OH', 'Northfield', 73),
  ('Fort Smith', false, 'AR', 'Namekagon', 74),
  ('Clearwater', false, 'FL', 'Elmside', 75),
  ('Seattle', true, 'WA', 'Londonderry', 76),
  ('Gainesville', true, 'GA', 'Badeau', 77),
  ('Modesto', true, 'CA', 'Lyons', 78),
  ('Austin', true, 'TX', 'Hanson', 79),
  ('Arlington', true, 'TX', 'Lindbergh', 80),
  ('Corpus Christi', true, 'TX', 'Corscot', 81),
  ('Newark', false, 'NJ', 'Haas', 82),
  ('Clearwater', false, 'FL', 'Vidon', 83),
  ('Wichita Falls', true, 'TX', 'Eliot', 84),
  ('West Hartford', true, 'CT', 'Lakewood', 85),
  ('Lawrenceville', false, 'GA', 'Tomscot', 86),
  ('Savannah', true, 'GA', 'Laurel', 87),
  ('Iowa City', true, 'IA', 'Ludington', 88),
  ('Spartanburg', false, 'SC', 'Pleasure', 89),
  ('Migrate', false, 'KY', 'Sachtjen', 90),
  ('Decatur', true, 'GA', 'Pine View', 91),
  ('Corpus Christi', true, 'TX', 'Corscot', 92),
  ('Jamaica', true, 'NY', 'Dayton', 93),
  ('New Orleans', true, 'LA', 'Everett', 94),
  ('Fort Lauderdale', true, 'FL', 'Bartelt', 95),
  ('Lancaster', true, 'PA', 'Sachs', 96),
  ('Henderson', false, 'NV', 'Becker', 97),
  ('Sioux Falls', true, 'SD', 'Northwestern', 98),
  ('Washington', true, 'DC', 'Burrows', 99),
  ('Bloomington', true, 'IN', 'Randy', 100),
  ('Laurel', false, 'MD', 'Farragut', 101),
  ('San Francisco', true, 'CA', 'Lotheville', 102),
  ('Fairfield', true, 'CT', 'Starling', 103),
  ('Knoxville', false, 'TN', 'Dryden', 104),
  ('San Antonio', true, 'TX', 'Vera', 105),
  ('Joliet', true, 'IL', 'Melvin', 106),
  ('Washington', false, 'DC', 'Loftsgordon', 107),
  ('New York City', false, 'NY', 'Florence', 108),
  ('Cincinnati', true, 'OH', 'Sachs', 109),
  ('Sioux Falls', false, 'SD', 'Moulton', 110),
  ('Pittsburgh', false, 'PA', 'Eggendart', 111),
  ('Salt Lake City', true, 'UT', 'Everett', 112),
  ('Cincinnati', false, 'OH', 'Merchant', 113),
  ('East Saint Louis', false, 'IL', 'Columbus', 114),
  ('New York City', true, 'NY', 'Anhalt', 115),
  ('Levittown', false, 'PA', 'Hintze', 116),
  ('Washington', false, 'DC', 'Crowley', 117),
  ('Carol Stream', false, 'IL', 'Anthes', 118),
  ('Houston', false, 'TX', 'Crest Line', 119),
  ('Gainesville', false, 'FL', 'Bashford', 120),
  ('Oklahoma City', false, 'OK', 'Ridgeway', 121),
  ('Riverside', true, 'CA', 'Hauk', 122),
  ('Jackson', false, 'MS', 'Sauthoff', 123),
  ('Buffalo', false, 'NY', 'Cambridge', 124),
  ('Tampa', false, 'FL', 'Evergreen', 125),
  ('Mobile', false, 'AL', 'Hayes', 126),
  ('Olympia', false, 'WA', 'Lawn', 127),
  ('Panama City', true, 'FL', 'Redwing', 128),
  ('Miami', false, 'FL', 'Esch', 129),
  ('Lincoln', false, 'NE', 'Crest Line', 130),
  ('Austin', true, 'TX', 'Weeping Birch', 131),
  ('Tampa', true, 'FL', 'Warner', 132),
  ('Elizabeth', false, 'NJ', 'Amoth', 133),
  ('Fullerton', true, 'CA', 'Sauthoff', 134),
  ('Atlanta', true, 'GA', 'Boyd', 135),
  ('Sioux Falls', false, 'SD', 'Morning', 136),
  ('Monroe', true, 'LA', 'Messerschmidt', 137),
  ('Fort Lauderdale', false, 'FL', 'Johnson', 138),
  ('San Jose', true, 'CA', 'Eggendart', 139),
  ('Portland', true, 'OR', 'Summerview', 140),
  ('Allentown', true, 'PA', 'Granby', 141),
  ('Fresno', false, 'CA', 'Cody', 142),
  ('Dayton', false, 'OH', 'Browning', 143),
  ('Burbank', true, 'CA', 'Gale', 144),
  ('Pittsburgh', false, 'PA', 'Shopko', 145),
  ('Washington', true, 'DC', '4th', 146),
  ('Birmingham', false, 'AL', 'Lakewood Gardens', 147),
  ('Arlington', true, 'VA', 'Oak Valley', 148),
  ('Davenport', false, 'IA', 'Hayes', 149),
  ('Rochester', true, 'NY', 'Sutteridge', 150),
  ('Albany', true, 'NY', 'Summerview', 151),
  ('Cleveland', false, 'OH', 'Lerdahl', 152),
  ('Minneapolis', false, 'MN', 'Blaine', 153),
  ('Trenton', true, 'NJ', 'Delladonna', 154),
  ('Santa Fe', true, 'NM', 'Grayhawk', 155),
  ('Houston', true, 'TX', 'Carpenter', 156),
  ('Cleveland', true, 'OH', 'Loftsgordon', 157),
  ('Mesquite', false, 'TX', 'Harbort', 158),
  ('Milwaukee', true, 'WI', 'Barby', 159),
  ('Gainesville', false, 'FL', 'American', 160),
  ('San Jose', true, 'CA', 'Maywood', 161),
  ('Saint Paul', true, 'MN', 'Homewood', 162),
  ('Tampa', false, 'FL', 'Pepper Wood', 163),
  ('Rochester', false, 'NY', 'Duke', 164),
  ('Amarillo', true, 'TX', 'Atwood', 165),
  ('Los Angeles', false, 'CA', 'Prairieview', 166),
  ('Pensacola', false, 'FL', 'Sherman', 167),
  ('Washington', false, 'DC', 'Heath', 168),
  ('Denver', false, 'CO', 'Sloan', 169),
  ('San Jose', false, 'CA', 'Algoma', 170),
  ('Wichita', true, 'KS', 'Reinke', 171),
  ('Spokane', false, 'WA', 'Forest Run', 172),
  ('Mesa', true, 'AZ', 'Green Ridge', 173),
  ('Erie', true, 'PA', 'Ryan', 174),
  ('New York City', false, 'NY', 'Crest Line', 175),
  ('Atlanta', false, 'GA', 'Little Fleur', 176),
  ('New Orleans', true, 'LA', 'Mifflin', 177),
  ('Jackson', false, 'MS', 'Golf Course', 178),
  ('Orlando', false, 'FL', 'Park Meadow', 179),
  ('High Point', false, 'NC', 'Barby', 180),
  ('Houston', true, 'TX', 'Becker', 181),
  ('Indianapolis', true, 'IN', 'Bartillon', 182),
  ('Billings', false, 'MT', 'Declaration', 183),
  ('Seattle', true, 'WA', 'Superior', 184),
  ('San Francisco', false, 'CA', 'Almo', 185),
  ('Charleston', true, 'SC', 'Debs', 186),
  ('Bronx', false, 'NY', 'Ridgeway', 187),
  ('New Orleans', false, 'LA', 'Hermina', 188),
  ('Boston', true, 'MA', 'Lakewood Gardens', 189),
  ('Long Beach', true, 'CA', 'Elgar', 190),
  ('Lexington', false, 'KY', 'Redwing', 191),
  ('Scottsdale', true, 'AZ', 'Loeprich', 192),
  ('North Port', true, 'FL', 'Derek', 193),
  ('Glendale', false, 'CA', 'Crowley', 194),
  ('Jacksonville', true, 'FL', 'Petterle', 195),
  ('Muncie', false, 'IN', 'Lotheville', 196),
  ('Houston', true, 'TX', 'Rutledge', 197),
  ('Tacoma', true, 'WA', 'Arkansas', 198),
  ('Lima', true, 'OH', 'Bartillon', 199),
  ('Bridgeport', false, 'CT', 'Bashford', 200),
  ('Memphis', true, 'TN', 'Linden', 201),
  ('Saint Louis', true, 'MO', 'Marquette', 202),
  ('Detroit', false, 'MI', 'Sunbrook', 203),
  ('Washington', false, 'DC', 'Logan', 204),
  ('Boulder', false, 'CO', 'Porter', 205),
  ('Fresno', true, 'CA', 'Doe Crossing', 206),
  ('Philadelphia', true, 'PA', 'Dayton', 207),
  ('Shawnee Mission', true, 'KS', 'Summer Ridge', 208),
  ('Detroit', false, 'MI', 'Erie', 209),
  ('Lexington', true, 'KY', 'Steensland', 210),
  ('Jacksonville', false, 'FL', 'Leroy', 211),
  ('Meridian', false, 'MS', 'Gina', 212),
  ('Montgomery', true, 'AL', 'Prairieview', 213),
  ('Durham', false, 'NC', 'Meadow Ridge', 214),
  ('Fresno', true, 'CA', 'Burrows', 215),
  ('Oklahoma City', true, 'OK', 'Bunting', 216),
  ('Jackson', true, 'MS', 'Monica', 217),
  ('Orlando', true, 'FL', 'Blaine', 218),
  ('Saint Cloud', true, 'MN', 'Dryden', 219),
  ('New Orleans', true, 'LA', 'Basil', 220),
  ('San Diego', true, 'CA', 'Schlimgen', 221),
  ('Fresno', true, 'CA', 'Vera', 222),
  ('New York City', true, 'NY', 'Garrison', 223),
  ('Paterson', true, 'NJ', 'Continental', 224),
  ('Gary', true, 'IN', 'Schlimgen', 225),
  ('Annapolis', true, 'MD', 'Pleasure', 226),
  ('Shawnee Mission', true, 'KS', 'Farmco', 227),
  ('Amarillo', false, 'TX', 'Schmedeman', 228),
  ('Billings', true, 'MT', 'Buhler', 229),
  ('Sacramento', true, 'CA', 'Arizona', 230),
  ('Wichita', false, 'KS', 'Stephen', 231),
  ('Monticello', false, 'MN', 'Express', 232),
  ('Birmingham', true, 'AL', 'Fulton', 233),
  ('Santa Monica', true, 'CA', 'Del Sol', 234),
  ('Oklahoma City', false, 'OK', 'Beilfuss', 235),
  ('Fort Wayne', false, 'IN', '4th', 236),
  ('Cincinnati', false, 'OH', 'Lakeland', 237),
  ('Scranton', true, 'PA', 'Lindbergh', 238),
  ('Houston', true, 'TX', 'Arizona', 239),
  ('Trenton', true, 'NJ', 'Utah', 240),
  ('El Paso', true, 'TX', 'Novick', 241),
  ('Metairie', false, 'LA', 'Twin Pines', 242),
  ('Nashville', true, 'TN', 'American', 243),
  ('Bowie', true, 'MD', 'Veith', 244),
  ('Toledo', false, 'OH', 'Ohio', 245),
  ('Lawrenceville', false, 'GA', 'Haas', 246),
  ('Terre Haute', true, 'IN', 'Chinook', 247),
  ('Troy', true, 'MI', 'Debs', 248),
  ('Saint Paul', true, 'MN', 'Sunnyside', 249),
  ('Augusta', true, 'GA', 'Harbort', 250),
  ('Pittsburgh', false, 'PA', 'Debs', 251),
  ('Idaho Falls', true, 'ID', 'Thierer', 252),
  ('New York City', false, 'NY', 'Schiller', 253),
  ('Chicago', true, 'IL', 'Aberg', 254),
  ('Fort Worth', false, 'TX', 'Hoffman', 255),
  ('New York City', true, 'NY', 'Rutledge', 256),
  ('Denver', true, 'CO', 'Kropf', 257),
  ('Daytona Beach', true, 'FL', 'Sage', 258),
  ('San Francisco', true, 'CA', '1st', 259),
  ('Akron', false, 'OH', 'Prairieview', 260),
  ('Bronx', false, 'NY', 'Kinsman', 261),
  ('Minneapolis', false, 'MN', 'Hallows', 262),
  ('Sacramento', false, 'CA', 'Ilene', 263),
  ('Little Rock', false, 'AR', 'Oak Valley', 264),
  ('Washington', true, 'DC', 'Kinsman', 265),
  ('Springfield', true, 'MA', 'Service', 266),
  ('El Paso', true, 'TX', 'Graceland', 267),
  ('Minneapolis', false, 'MN', 'Havey', 268),
  ('Baton Rouge', true, 'LA', 'Wayridge', 269),
  ('Mobile', true, 'AL', 'Springview', 270),
  ('Sarasota', false, 'FL', 'Monica', 271),
  ('Miami', false, 'FL', 'Maywood', 272),
  ('Macon', true, 'GA', 'Glacier Hill', 273),
  ('Springfield', true, 'MO', 'Kenwood', 274),
  ('Birmingham', false, 'AL', 'Cottonwood', 275),
  ('Carson City', true, 'NV', 'Red Cloud', 276),
  ('New York City', false, 'NY', 'Leroy', 277),
  ('San Diego', false, 'CA', 'Lotheville', 278),
  ('New Brunswick', false, 'NJ', 'Dayton', 279),
  ('Trenton', false, 'NJ', 'Glendale', 280),
  ('Pittsburgh', true, 'PA', 'Lakewood Gardens', 281),
  ('Atlanta', false, 'GA', 'Golf', 282),
  ('Omaha', false, 'NE', 'Continental', 283),
  ('Indianapolis', true, 'IN', 'School', 284),
  ('Minneapolis', true, 'MN', 'Paget', 285),
  ('Lincoln', true, 'NE', 'Chinook', 286),
  ('El Paso', false, 'TX', 'Morningstar', 287),
  ('Roanoke', true, 'VA', 'Cody', 288),
  ('Erie', false, 'PA', 'Atwood', 289),
  ('New York City', true, 'NY', 'Manitowish', 290),
  ('San Antonio', true, 'TX', 'Northport', 291),
  ('Montgomery', false, 'AL', 'Eagan', 292),
  ('Albany', true, 'NY', 'Messerschmidt', 293),
  ('Schaumburg', false, 'IL', 'Porter', 294),
  ('Fort Worth', false, 'TX', 'Corben', 295),
  ('Houston', false, 'TX', 'Thompson', 296),
  ('Chicago', true, 'IL', 'Jackson', 297),
  ('Green Bay', true, 'WI', 'Vermont', 298),
  ('Jacksonville', true, 'FL', 'Veith', 299),
  ('Suffolk', true, 'VA', 'Summer Ridge', 300),
  ('Pittsburgh', false, 'PA', 'Lukken', 301),
  ('Saint Paul', true, 'MN', 'Dahle', 302),
  ('Flint', true, 'MI', 'Lakewood Gardens', 303),
  ('San Francisco', false, 'CA', 'Huxley', 304),
  ('Norman', true, 'OK', 'Pepper Wood', 305),
  ('Eugene', true, 'OR', 'Thackeray', 306),
  ('Houston', false, 'TX', 'Dapin', 307),
  ('Philadelphia', true, 'PA', 'Utah', 308),
  ('Jamaica', false, 'NY', 'Buena Vista', 309),
  ('Baltimore', true, 'MD', 'Cascade', 310),
  ('Indianapolis', true, 'IN', 'Randy', 311),
  ('San Antonio', true, 'TX', 'Jackson', 312),
  ('Roanoke', false, 'VA', 'Thierer', 313),
  ('Wichita', true, 'KS', 'Bultman', 314),
  ('Inglewood', false, 'CA', 'Forest Dale', 315),
  ('Saint Paul', true, 'MN', 'Washington', 316),
  ('Hagerstown', true, 'MD', 'Sugar', 317),
  ('Tyler', false, 'TX', 'Russell', 318),
  ('Dallas', true, 'TX', 'Charing Cross', 319),
  ('Pasadena', true, 'CA', 'Paget', 320),
  ('Chicago', false, 'IL', 'Stang', 321),
  ('Allentown', true, 'PA', 'Linden', 322),
  ('Savannah', false, 'GA', 'Hoffman', 323),
  ('Pasadena', false, 'CA', 'Towne', 324),
  ('Kansas City', false, 'MO', 'Spohn', 325),
  ('Roanoke', false, 'VA', 'Ridge Oak', 326),
  ('Trenton', false, 'NJ', 'Stuart', 327),
  ('Dallas', true, 'TX', 'Ridgeway', 328),
  ('Portland', false, 'OR', 'Butternut', 329),
  ('Spokane', true, 'WA', 'Dorton', 330),
  ('Dallas', true, 'TX', 'Canary', 331),
  ('Boston', true, 'MA', 'Rutledge', 332),
  ('Oxnard', true, 'CA', 'Erie', 333),
  ('Atlanta', false, 'GA', 'Londonderry', 334),
  ('Los Angeles', true, 'CA', 'Oak Valley', 335),
  ('Lexington', true, 'KY', 'Ilene', 336),
  ('Pensacola', false, 'FL', 'Sheridan', 337),
  ('Orlando', true, 'FL', 'Larry', 338),
  ('Jacksonville', false, 'FL', 'Loeprich', 339),
  ('Fort Smith', true, 'AR', 'Johnson', 340),
  ('Cleveland', false, 'OH', 'Sunnyside', 341),
  ('Colorado Springs', false, 'CO', 'Pleasure', 342),
  ('Virginia Beach', false, 'VA', 'Merry', 343),
  ('Oklahoma City', false, 'OK', 'Sachtjen', 344),
  ('Atlanta', true, 'GA', 'Kropf', 345),
  ('Portland', true, 'OR', 'Mcguire', 346),
  ('Fort Wayne', true, 'IN', 'Debs', 347),
  ('Raleigh', true, 'NC', 'Eagle Crest', 348),
  ('Miami', true, 'FL', 'Delaware', 349),
  ('Lubbock', false, 'TX', 'Thompson', 350),
  ('San Jose', true, 'CA', 'Mcguire', 351),
  ('Paterson', true, 'NJ', 'Vidon', 352),
  ('Sacramento', false, 'CA', 'Grover', 353),
  ('Ocala', true, 'FL', 'Del Mar', 354),
  ('New York City', false, 'NY', 'Bultman', 355),
  ('Dallas', true, 'TX', 'Old Shore', 356),
  ('Colorado Springs', true, 'CO', 'Meadow Valley', 357),
  ('Raleigh', true, 'NC', 'American Ash', 358),
  ('Lexington', false, 'KY', 'Roxbury', 359),
  ('Wichita', true, 'KS', 'Gateway', 360),
  ('New York City', true, 'NY', 'Center', 361),
  ('Tacoma', true, 'WA', 'Moulton', 362),
  ('New Orleans', true, 'LA', 'Jana', 363),
  ('Hartford', true, 'CT', 'Mariners Cove', 364),
  ('Richmond', false, 'VA', 'Arizona', 365),
  ('Bakersfield', true, 'CA', 'Northland', 366),
  ('El Paso', true, 'TX', 'Westend', 367),
  ('Dallas', false, 'TX', 'Esch', 368),
  ('Chicago', true, 'IL', 'Schiller', 369),
  ('Columbia', true, 'SC', 'Blue Bill Park', 370),
  ('Arlington', true, 'TX', 'Hanson', 371),
  ('Columbus', false, 'GA', 'Lakeland', 372),
  ('Lincoln', false, 'NE', 'Rowland', 373),
  ('Honolulu', false, 'HI', 'Sachs', 374),
  ('Washington', false, 'DC', 'Rieder', 375),
  ('Gainesville', false, 'FL', 'Dunning', 376),
  ('Tacoma', true, 'WA', 'Muir', 377),
  ('Bronx', false, 'NY', 'Dayton', 378),
  ('Houston', true, 'TX', 'Forest', 379),
  ('Pittsburgh', false, 'PA', 'Messerschmidt', 380),
  ('Anaheim', true, 'CA', 'Stang', 381),
  ('Miami', true, 'FL', 'Ludington', 382),
  ('Fort Myers', false, 'FL', 'Crescent Oaks', 383),
  ('Peoria', true, 'IL', 'Superior', 384),
  ('Brooksville', true, 'FL', 'Heath', 385),
  ('Hartford', false, 'CT', 'Thierer', 386),
  ('Round Rock', true, 'TX', 'Ryan', 387),
  ('Durham', true, 'NC', 'Redwing', 388),
  ('Brooksville', true, 'FL', 'Havey', 389),
  ('San Jose', true, 'CA', 'Rutledge', 390),
  ('Minneapolis', false, 'MN', 'Gina', 391),
  ('Tampa', true, 'FL', 'Oakridge', 392),
  ('San Antonio', true, 'TX', 'Hallows', 393),
  ('Arlington', true, 'VA', 'Michigan', 394),
  ('East Saint Louis', false, 'IL', 'Dovetail', 395),
  ('Topeka', true, 'KS', 'Haas', 396),
  ('Augusta', true, 'GA', 'Calypso', 397),
  ('Hicksville', true, 'NY', 'Clarendon', 398),
  ('Orlando', true, 'FL', 'Maywood', 399),
  ('Boston', true, 'MA', 'Continental', 400),
  ('Whittier', true, 'CA', 'Thackeray', 401),
  ('Flint', true, 'MI', 'Sutherland', 402),
  ('Glendale', false, 'AZ', 'High Crossing', 403),
  ('Philadelphia', true, 'PA', 'Meadow Vale', 404),
  ('Baton Rouge', true, 'LA', 'Muir', 405),
  ('San Jose', false, 'CA', 'Golf View', 406),
  ('Columbia', true, 'SC', 'Toban', 407),
  ('Fairbanks', true, 'AK', 'Blaine', 408),
  ('Stamford', true, 'CT', 'Bartelt', 409),
  ('Washington', false, 'DC', 'Mayer', 410),
  ('Richmond', true, 'VA', 'Di Loreto', 411),
  ('Boise', false, 'ID', 'Karstens', 412),
  ('Oklahoma City', true, 'OK', 'Pawling', 413),
  ('Anaheim', false, 'CA', 'Kenwood', 414),
  ('Dallas', true, 'TX', 'Prentice', 415),
  ('Akron', true, 'OH', 'Victoria', 416),
  ('Anderson', false, 'IN', 'Straubel', 417),
  ('Chicago', true, 'IL', 'Clemons', 418),
  ('San Francisco', false, 'CA', 'Tennyson', 419),
  ('Columbus', false, 'OH', 'Kedzie', 420),
  ('Gatesville', true, 'TX', 'Ronald Regan', 421),
  ('New York City', false, 'NY', 'Summit', 422),
  ('Tulsa', false, 'OK', 'Dahle', 423),
  ('Washington', true, 'DC', 'Fair Oaks', 424),
  ('San Diego', true, 'CA', 'Grasskamp', 425),
  ('Youngstown', true, 'OH', 'Elka', 426),
  ('Baltimore', false, 'MD', 'Reindahl', 427),
  ('Sunnyvale', true, 'CA', 'Colorado', 428),
  ('Pensacola', true, 'FL', 'Garrison', 429),
  ('Omaha', false, 'NE', 'Calypso', 430),
  ('San Diego', true, 'CA', 'Superior', 431),
  ('Myrtle Beach', true, 'SC', 'Hooker', 432),
  ('Trenton', true, 'NJ', 'Ryan', 433),
  ('Minneapolis', false, 'MN', 'Crest Line', 434),
  ('Shreveport', true, 'LA', 'Pepper Wood', 435),
  ('Bakersfield', true, 'CA', 'Eggendart', 436),
  ('New Orleans', false, 'LA', 'Atwood', 437),
  ('New Castle', true, 'PA', 'Scofield', 438),
  ('Denver', true, 'CO', 'Paget', 439),
  ('Rochester', true, 'NY', 'Corben', 440),
  ('Las Vegas', true, 'NV', 'Stang', 441),
  ('Omaha', true, 'NE', 'Autumn Leaf', 442),
  ('Milwaukee', true, 'WI', 'Novick', 443),
  ('Bradenton', true, 'FL', 'Texas', 444),
  ('Wilmington', false, 'DE', 'Morning', 445),
  ('Brooklyn', false, 'NY', 'Memorial', 446),
  ('Honolulu', true, 'HI', 'Summer Ridge', 447),
  ('Jacksonville', true, 'FL', 'Badeau', 448),
  ('Jefferson City', true, 'MO', 'Twin Pines', 449),
  ('Washington', false, 'DC', 'Fair Oaks', 450),
  ('Spring Hill', true, 'FL', 'Milwaukee', 451),
  ('Sacramento', false, 'CA', 'Dwight', 452),
  ('Houston', false, 'TX', 'Hovde', 453),
  ('Houston', false, 'TX', 'Mesta', 454),
  ('Anniston', false, 'AL', '2nd', 455),
  ('El Paso', false, 'TX', 'Garrison', 456),
  ('Washington', false, 'DC', 'Dayton', 457),
  ('Shreveport', true, 'LA', 'Erie', 458),
  ('Green Bay', false, 'WI', 'Larry', 459),
  ('Huntington Beach', false, 'CA', 'Sloan', 460),
  ('Louisville', false, 'KY', 'Sunbrook', 461),
  ('North Port', true, 'FL', 'Brentwood', 462),
  ('Brooklyn', false, 'NY', 'Village Green', 463),
  ('Flushing', false, 'NY', 'Bunting', 464),
  ('Birmingham', false, 'AL', 'Ryan', 465),
  ('Lexington', true, 'KY', 'Dennis', 466),
  ('Fort Worth', true, 'TX', 'Northfield', 467),
  ('Bakersfield', false, 'CA', 'Forest Dale', 468),
  ('Waterloo', false, 'IA', 'Rusk', 469),
  ('Salt Lake City', true, 'UT', 'American Ash', 470),
  ('Columbus', true, 'OH', 'Lerdahl', 471),
  ('Fairbanks', false, 'AK', 'East', 472),
  ('Madison', true, 'WI', 'Elka', 473),
  ('Los Angeles', true, 'CA', 'Spohn', 474),
  ('Phoenix', false, 'AZ', 'Rutledge', 475),
  ('El Paso', true, 'TX', 'Gale', 476),
  ('Pittsburgh', true, 'PA', 'Mandrake', 477),
  ('Watertown', false, 'MA', 'Luster', 478),
  ('New Haven', true, 'CT', 'Badeau', 479),
  ('Charlotte', false, 'NC', 'Almo', 480),
  ('Harrisburg', true, 'PA', 'Vernon', 481),
  ('Houston', true, 'TX', 'Dapin', 482),
  ('Peoria', false, 'IL', 'Erie', 483),
  ('Indianapolis', true, 'IN', 'Erie', 484),
  ('El Paso', true, 'TX', 'Maryland', 485),
  ('Waterbury', true, 'CT', 'Sundown', 486),
  ('Santa Barbara', false, 'CA', 'Mandrake', 487),
  ('Lincoln', true, 'NE', 'Calypso', 488),
  ('Farmington', false, 'MI', 'Crowley', 489),
  ('Oklahoma City', true, 'OK', 'Sommers', 490),
  ('Terre Haute', true, 'IN', 'Pennsylvania', 491),
  ('Mesa', true, 'AZ', 'Welch', 492),
  ('Los Angeles', true, 'CA', 'Orin', 493),
  ('Roanoke', true, 'VA', 'Debs', 494),
  ('Jackson', false, 'MS', 'Delladonna', 495),
  ('Pompano Beach', false, 'FL', 'Bartelt', 496),
  ('El Paso', false, 'TX', 'Pearson', 497),
  ('Gilbert', false, 'AZ', 'Dorton', 498),
  ('El Paso', true, 'TX', 'Westport', 499),
  ('Greensboro', false, 'NC', 'Coleman', 500),
  ('Winston Salem', true, 'NC', 'Judy', 501),
  ('Memphis', false, 'TN', 'New Castle', 502),
  ('Charlotte', false, 'NC', 'Sundown', 503),
  ('Providence', true, 'RI', 'Straubel', 504),
  ('Fort Worth', true, 'TX', 'Atwood', 505),
  ('Akron', false, 'OH', 'Cardinal', 506),
  ('Amarillo', false, 'TX', 'Corry', 507),
  ('Fort Myers', false, 'FL', 'Laurel', 508),
  ('Knoxville', false, 'TN', 'Hintze', 509),
  ('Grand Rapids', true, 'MI', 'Old Gate', 510),
  ('Jersey City', true, 'NJ', 'Wayridge', 511),
  ('Charleston', false, 'WV', 'Heath', 512),
  ('Birmingham', false, 'AL', 'Sullivan', 513),
  ('Baltimore', true, 'MD', 'Meadow Valley', 514),
  ('Brooklyn', false, 'NY', 'Heffernan', 515),
  ('Huntsville', true, 'TX', 'Rieder', 516),
  ('North Little Rock', true, 'AR', 'Tomscot', 517),
  ('Las Vegas', true, 'NV', 'Pleasure', 518),
  ('San Antonio', false, 'TX', 'Atwood', 519),
  ('Scottsdale', false, 'AZ', 'Fremont', 520),
  ('Waco', false, 'TX', 'Anniversary', 521),
  ('Yakima', false, 'WA', 'Buell', 522),
  ('Charleston', false, 'SC', 'Bartillon', 523),
  ('New Castle', true, 'PA', 'Park Meadow', 524),
  ('Fort Wayne', true, 'IN', 'Grasskamp', 525),
  ('Chicago', false, 'IL', 'Fallview', 526),
  ('Jackson', true, 'MS', 'Maple', 527),
  ('Huntington', true, 'WV', 'Farwell', 528),
  ('Tacoma', true, 'WA', 'Carey', 529),
  ('Colorado Springs', true, 'CO', 'Clarendon', 530),
  ('Colorado Springs', true, 'CO', '1st', 531),
  ('Spring Hill', true, 'FL', 'Green', 532),
  ('Harrisburg', false, 'PA', 'La Follette', 533),
  ('Springfield', true, 'MA', 'Moulton', 534),
  ('Temple', true, 'TX', 'Cardinal', 535),
  ('Washington', false, 'DC', 'Erie', 536),
  ('Huntington', true, 'WV', 'Bartelt', 537),
  ('Fort Lauderdale', false, 'FL', 'Golden Leaf', 538),
  ('Aurora', true, 'CO', 'Marcy', 539),
  ('Prescott', false, 'AZ', 'Service', 540),
  ('Pueblo', false, 'CO', 'Morrow', 541),
  ('Jackson', true, 'MS', 'Blackbird', 542),
  ('Florence', true, 'SC', 'Morning', 543),
  ('Mobile', true, 'AL', 'Sage', 544),
  ('Salt Lake City', true, 'UT', 'Sage', 545),
  ('Bradenton', true, 'FL', 'Mitchell', 546),
  ('Houston', false, 'TX', 'Nobel', 547),
  ('Sacramento', true, 'CA', 'Drewry', 548),
  ('Boston', false, 'MA', 'Hoepker', 549),
  ('Corona', false, 'CA', 'Hansons', 550),
  ('Bloomington', false, 'IN', 'Monument', 551),
  ('Ogden', false, 'UT', 'Texas', 552),
  ('Washington', true, 'DC', 'Burning Wood', 553),
  ('Reno', true, 'NV', 'Tony', 554),
  ('Atlanta', true, 'GA', 'Nelson', 555),
  ('Spartanburg', true, 'SC', 'Montana', 556),
  ('Phoenix', true, 'AZ', 'Bay', 557),
  ('Evansville', false, 'IN', 'Ryan', 558),
  ('New Castle', true, 'PA', 'Scoville', 559),
  ('Palatine', true, 'IL', 'Golf', 560),
  ('San Jose', false, 'CA', 'Loeprich', 561),
  ('Cincinnati', false, 'OH', 'Marcy', 562),
  ('Tampa', true, 'FL', 'Golf Course', 563),
  ('Denton', true, 'TX', 'Norway Maple', 564),
  ('Chicago', true, 'IL', 'Hollow Ridge', 565),
  ('Washington', true, 'DC', 'Armistice', 566),
  ('Tampa', true, 'FL', 'Blue Bill Park', 567),
  ('Houston', true, 'TX', 'Norway Maple', 568),
  ('Oklahoma City', true, 'OK', 'Service', 569),
  ('Port Saint Lucie', false, 'FL', 'Gale', 570),
  ('Boston', false, 'MA', 'Beilfuss', 571),
  ('Washington', false, 'DC', 'Ridge Oak', 572),
  ('Indianapolis', true, 'IN', 'Bartillon', 573),
  ('San Antonio', true, 'TX', 'Stephen', 574),
  ('Charleston', false, 'WV', 'Crest Line', 575),
  ('Shawnee Mission', false, 'KS', 'Southridge', 576),
  ('Clearwater', true, 'FL', 'Fremont', 577),
  ('New Orleans', false, 'LA', 'Columbus', 578),
  ('Arlington', false, 'TX', 'Golf', 579),
  ('San Mateo', true, 'CA', 'Scofield', 580),
  ('Nashville', false, 'TN', 'Bluejay', 581),
  ('Las Vegas', false, 'NV', 'Fieldstone', 582),
  ('Billings', false, 'MT', 'Starling', 583),
  ('Las Vegas', false, 'NV', 'Carpenter', 584),
  ('New Orleans', true, 'LA', 'Rockefeller', 585),
  ('San Francisco', false, 'CA', 'Scoville', 586),
  ('Washington', false, 'DC', 'Barby', 587),
  ('Baltimore', true, 'MD', 'Daystar', 588),
  ('West Palm Beach', true, 'FL', 'Prentice', 589),
  ('Columbus', false, 'OH', 'Northview', 590),
  ('Milwaukee', true, 'WI', 'Schiller', 591),
  ('New York City', true, 'NY', 'Stephen', 592),
  ('San Diego', false, 'CA', 'John Wall', 593),
  ('Winston Salem', true, 'NC', 'Sycamore', 594),
  ('Topeka', true, 'KS', 'Harper', 595),
  ('Richmond', true, 'VA', 'Waubesa', 596),
  ('Huntsville', false, 'AL', 'Judy', 597),
  ('Bismarck', true, 'ND', 'Drewry', 598),
  ('Homestead', false, 'FL', 'Marcy', 599),
  ('San Jose', true, 'CA', 'Comanche', 600),
  ('Young America', true, 'MN', 'Roth', 601),
  ('Seattle', false, 'WA', 'New Castle', 602),
  ('Seattle', true, 'WA', 'Messerschmidt', 603),
  ('Arlington', true, 'VA', '1st', 604),
  ('Mobile', false, 'AL', 'Carioca', 605),
  ('Rochester', true, 'NY', 'Springs', 606),
  ('Birmingham', false, 'AL', 'Kennedy', 607),
  ('Stockton', false, 'CA', 'Monterey', 608),
  ('Little Rock', true, 'AR', 'Emmet', 609),
  ('Knoxville', false, 'TN', 'Grasskamp', 610),
  ('Orlando', true, 'FL', 'Monterey', 611),
  ('Pomona', false, 'CA', 'Florence', 612),
  ('Fort Myers', false, 'FL', 'Hayes', 613),
  ('Tacoma', true, 'WA', 'Bonner', 614),
  ('Orlando', false, 'FL', 'Linden', 615),
  ('Boston', true, 'MA', 'Talmadge', 616),
  ('Stockton', true, 'CA', 'Talmadge', 617),
  ('Evansville', false, 'IN', 'American', 618),
  ('Racine', false, 'WI', '2nd', 619),
  ('Salem', false, 'OR', 'Pine View', 620),
  ('Grand Junction', false, 'CO', 'Larry', 621),
  ('Hialeah', true, 'FL', 'Superior', 622),
  ('Akron', false, 'OH', 'Coleman', 623),
  ('Bridgeport', true, 'CT', 'Old Gate', 624),
  ('Grand Rapids', false, 'MI', 'Farwell', 625),
  ('Kansas City', false, 'MO', 'Sage', 626),
  ('Los Angeles', false, 'CA', 'Mcguire', 627),
  ('Seattle', true, 'WA', 'Bluestem', 628),
  ('Bakersfield', false, 'CA', 'Badeau', 629),
  ('Lakeland', true, 'FL', 'Scoville', 630),
  ('Oklahoma City', true, 'OK', 'Bobwhite', 631),
  ('Tulsa', true, 'OK', 'Amoth', 632),
  ('Washington', false, 'DC', 'Mockingbird', 633),
  ('Erie', true, 'PA', 'Mariners Cove', 634),
  ('Baltimore', false, 'MD', 'Onsgard', 635),
  ('Santa Ana', false, 'CA', 'Vernon', 636),
  ('Johnstown', false, 'PA', 'Southridge', 637),
  ('Salt Lake City', true, 'UT', 'Meadow Ridge', 638),
  ('Glendale', true, 'CA', 'Iowa', 639),
  ('Memphis', false, 'TN', 'Warrior', 640),
  ('Watertown', true, 'MA', 'Canary', 641),
  ('Iowa City', true, 'IA', 'Bowman', 642),
  ('Aurora', false, 'CO', 'Duke', 643),
  ('Los Angeles', false, 'CA', 'Hazelcrest', 644),
  ('Boca Raton', false, 'FL', 'Boyd', 645),
  ('Boise', false, 'ID', 'International', 646),
  ('Santa Fe', true, 'NM', 'Amoth', 647),
  ('Birmingham', true, 'AL', 'Hoard', 648),
  ('Sacramento', false, 'CA', 'Pierstorff', 649),
  ('New York City', true, 'NY', 'Clyde Gallagher', 650),
  ('Miami', false, 'FL', 'Lunder', 651),
  ('Trenton', true, 'NJ', 'Scoville', 652),
  ('Panama City', false, 'FL', 'Schlimgen', 653),
  ('Naples', true, 'FL', 'Sutteridge', 654),
  ('Carol Stream', false, 'IL', 'Gale', 655),
  ('Norwalk', true, 'CT', 'Florence', 656),
  ('El Paso', false, 'TX', 'Basil', 657),
  ('Baton Rouge', true, 'LA', 'Mariners Cove', 658),
  ('Clearwater', false, 'FL', 'Dixon', 659),
  ('Oklahoma City', false, 'OK', 'Tony', 660),
  ('Jackson', false, 'MS', 'Fuller', 661),
  ('Norcross', true, 'GA', '6th', 662),
  ('Honolulu', false, 'HI', 'Nobel', 663),
  ('Salt Lake City', true, 'UT', 'Jay', 664),
  ('Hayward', true, 'CA', 'Browning', 665),
  ('Austin', false, 'TX', 'Swallow', 666),
  ('Tucson', true, 'AZ', 'Leroy', 667),
  ('Dayton', false, 'OH', 'Starling', 668),
  ('Saint Louis', false, 'MO', 'Tony', 669),
  ('Englewood', false, 'CO', 'Elka', 670),
  ('Panama City', false, 'FL', 'Randy', 671),
  ('Seattle', false, 'WA', 'Anniversary', 672),
  ('Lubbock', false, 'TX', 'Charing Cross', 673),
  ('Lake Worth', true, 'FL', 'Fairview', 674),
  ('Boulder', false, 'CO', '5th', 675),
  ('Louisville', true, 'KY', 'Red Cloud', 676),
  ('Brooklyn', false, 'NY', 'Hoard', 677),
  ('Homestead', false, 'FL', 'Anderson', 678),
  ('Denver', false, 'CO', 'Kingsford', 679),
  ('Silver Spring', false, 'MD', 'Killdeer', 680),
  ('Huntsville', false, 'AL', 'Corry', 681),
  ('Detroit', false, 'MI', 'Old Gate', 682),
  ('Fresno', true, 'CA', 'Shoshone', 683),
  ('Houston', false, 'TX', 'Oneill', 684),
  ('Dayton', false, 'OH', 'Brickson Park', 685),
  ('Jefferson City', true, 'MO', 'Jackson', 686),
  ('Springfield', true, 'IL', 'Springs', 687),
  ('Greensboro', false, 'NC', 'Summer Ridge', 688),
  ('Memphis', false, 'TN', 'Pleasure', 689),
  ('San Francisco', true, 'CA', 'West', 690),
  ('Grand Rapids', true, 'MI', 'Ohio', 691),
  ('Boise', true, 'ID', 'Dawn', 692),
  ('Jacksonville', true, 'FL', 'Badeau', 693),
  ('Tulsa', false, 'OK', 'Mockingbird', 694),
  ('Saint Cloud', false, 'MN', 'Tennyson', 695),
  ('Young America', true, 'MN', 'Anderson', 696),
  ('Peoria', false, 'IL', 'Twin Pines', 697),
  ('New York City', true, 'NY', 'Bartelt', 698),
  ('Spokane', false, 'WA', 'Ryan', 699),
  ('El Paso', false, 'TX', 'Nobel', 700),
  ('Rochester', false, 'NY', 'Vera', 701),
  ('Austin', false, 'TX', 'Prairieview', 702),
  ('Corpus Christi', false, 'TX', 'Bartelt', 703),
  ('New Orleans', true, 'LA', 'New Castle', 704),
  ('Corpus Christi', true, 'TX', 'Johnson', 705),
  ('Port Saint Lucie', false, 'FL', 'Nevada', 706),
  ('Rochester', true, 'NY', 'Bluejay', 707),
  ('Bradenton', false, 'FL', 'Northland', 708),
  ('Portsmouth', false, 'NH', 'Killdeer', 709),
  ('Oklahoma City', true, 'OK', 'Onsgard', 710),
  ('Amarillo', false, 'TX', 'Darwin', 711),
  ('Boston', true, 'MA', 'Lillian', 712),
  ('Buffalo', false, 'NY', 'Superior', 713),
  ('Charlotte', true, 'NC', 'Brentwood', 714),
  ('Washington', true, 'DC', 'Lerdahl', 715),
  ('New Orleans', true, 'LA', 'La Follette', 716),
  ('Washington', true, 'DC', 'Golf Course', 717),
  ('Minneapolis', false, 'MN', 'Annamark', 718),
  ('Anchorage', false, 'AK', 'Clemons', 719),
  ('Austin', false, 'TX', 'Clove', 720),
  ('New York City', true, 'NY', 'Hooker', 721),
  ('Albany', false, 'NY', 'Burning Wood', 722),
  ('Washington', true, 'DC', 'Briar Crest', 723),
  ('Saint Augustine', true, 'FL', 'Cardinal', 724),
  ('Sacramento', true, 'CA', 'Miller', 725),
  ('Phoenix', false, 'AZ', 'Prentice', 726),
  ('Clearwater', true, 'FL', 'Troy', 727),
  ('Waco', true, 'TX', 'Badeau', 728),
  ('Columbus', false, 'GA', 'Dunning', 729),
  ('Charlotte', true, 'NC', 'Warbler', 730),
  ('Columbia', false, 'SC', 'Namekagon', 731),
  ('Cape Coral', false, 'FL', 'Graedel', 732),
  ('Decatur', false, 'GA', 'Bellgrove', 733),
  ('New Orleans', true, 'LA', 'Nova', 734),
  ('Iowa City', true, 'IA', 'Del Mar', 735),
  ('Washington', true, 'DC', 'Sycamore', 736),
  ('Charleston', false, 'WV', 'Bowman', 737),
  ('Jacksonville', false, 'FL', 'Southridge', 738),
  ('Portland', false, 'OR', 'Barnett', 739),
  ('Houston', false, 'TX', 'Lighthouse Bay', 740),
  ('Fort Worth', false, 'TX', 'Bayside', 741),
  ('Washington', true, 'DC', 'Northport', 742),
  ('Florence', true, 'SC', 'Tomscot', 743),
  ('Denver', false, 'CO', 'Cody', 744),
  ('Washington', true, 'DC', 'Bowman', 745),
  ('Washington', true, 'DC', 'Cherokee', 746),
  ('Phoenix', true, 'AZ', 'Dapin', 747),
  ('Southfield', true, 'MI', 'Eastwood', 748),
  ('Denver', true, 'CO', 'Fuller', 749),
  ('London', false, 'KY', 'Bowman', 750),
  ('Cambridge', true, 'MA', 'Scott', 751),
  ('Tulsa', false, 'OK', 'Tony', 752),
  ('Detroit', false, 'MI', 'Carpenter', 753),
  ('Englewood', true, 'CO', 'Summerview', 754),
  ('White Plains', true, 'NY', 'Sauthoff', 755),
  ('Erie', true, 'PA', 'Melrose', 756),
  ('Indianapolis', true, 'IN', 'Reinke', 757),
  ('Greensboro', true, 'NC', 'Cody', 758),
  ('Albany', false, 'NY', 'Sloan', 759),
  ('Philadelphia', false, 'PA', 'Logan', 760),
  ('Stamford', true, 'CT', 'Summit', 761),
  ('Houston', false, 'TX', 'Bartillon', 762),
  ('Port Charlotte', true, 'FL', 'Novick', 763),
  ('Austin', false, 'TX', 'Nobel', 764),
  ('Anchorage', false, 'AK', 'Grasskamp', 765),
  ('Corpus Christi', true, 'TX', 'Brickson Park', 766),
  ('Orlando', false, 'FL', 'Waxwing', 767),
  ('San Francisco', true, 'CA', 'Coleman', 768),
  ('Laredo', false, 'TX', 'Michigan', 769),
  ('Homestead', false, 'FL', 'Badeau', 770),
  ('Sacramento', false, 'CA', 'Dottie', 771),
  ('New York City', false, 'NY', 'Eagan', 772),
  ('Fort Lauderdale', true, 'FL', 'Pankratz', 773),
  ('Columbus', false, 'OH', 'Comanche', 774),
  ('Roanoke', false, 'VA', 'Rutledge', 775),
  ('Springfield', true, 'IL', 'Roxbury', 776),
  ('Hartford', true, 'CT', 'Muir', 777),
  ('Baton Rouge', false, 'LA', 'Bellgrove', 778),
  ('Lexington', false, 'KY', 'Bluejay', 779),
  ('Chicago', true, 'IL', 'Lyons', 780),
  ('Newark', false, 'DE', 'Knutson', 781),
  ('Phoenix', true, 'AZ', 'Shasta', 782),
  ('Monticello', false, 'MN', 'Ludington', 783),
  ('Omaha', true, 'NE', 'Namekagon', 784),
  ('South Bend', false, 'IN', 'Dryden', 785),
  ('Canton', true, 'OH', 'Miller', 786),
  ('Saginaw', true, 'MI', 'Independence', 787),
  ('Garland', true, 'TX', 'Texas', 788),
  ('Ashburn', false, 'VA', 'Independence', 789),
  ('Brockton', false, 'MA', 'Upham', 790),
  ('Metairie', false, 'LA', 'Macpherson', 791),
  ('Fort Lauderdale', false, 'FL', 'Mccormick', 792),
  ('Houston', false, 'TX', 'Mcbride', 793),
  ('Oklahoma City', false, 'OK', 'Granby', 794),
  ('Fairfax', true, 'VA', 'Grasskamp', 795),
  ('San Diego', false, 'CA', 'Kings', 796),
  ('El Paso', true, 'TX', 'Farragut', 797),
  ('Raleigh', false, 'NC', 'Park Meadow', 798),
  ('Miami', false, 'FL', 'Sycamore', 799),
  ('Cleveland', true, 'OH', 'Briar Crest', 800),
  ('Amarillo', false, 'TX', 'Lien', 801),
  ('Tallahassee', false, 'FL', 'Butternut', 802),
  ('High Point', true, 'NC', 'Porter', 803),
  ('Detroit', false, 'MI', 'Park Meadow', 804),
  ('Dallas', false, 'TX', 'Kensington', 805),
  ('Albuquerque', false, 'NM', 'Aberg', 806),
  ('Honolulu', false, 'HI', 'Gerald', 807),
  ('Fairbanks', true, 'AK', 'Arizona', 808),
  ('Oklahoma City', true, 'OK', 'Buell', 809),
  ('Dallas', true, 'TX', 'Vidon', 810),
  ('Huntington', true, 'WV', 'Alpine', 811),
  ('North Hollywood', false, 'CA', 'Golf View', 812),
  ('Beaumont', true, 'TX', 'Bellgrove', 813),
  ('Greenville', false, 'SC', 'Fordem', 814),
  ('Kansas City', false, 'MO', 'Lakewood Gardens', 815),
  ('Kansas City', false, 'MO', 'Bartelt', 816),
  ('New Orleans', false, 'LA', 'Troy', 817),
  ('New York City', false, 'NY', '5th', 818),
  ('Milwaukee', false, 'WI', 'Hoepker', 819),
  ('South Bend', false, 'IN', 'Fremont', 820),
  ('Dallas', false, 'TX', 'Spenser', 821),
  ('Topeka', false, 'KS', 'Oneill', 822),
  ('Mobile', true, 'AL', 'Bashford', 823),
  ('Amarillo', true, 'TX', 'Summer Ridge', 824),
  ('Washington', false, 'DC', 'Ilene', 825),
  ('Greensboro', true, 'NC', 'Vera', 826),
  ('Minneapolis', false, 'MN', 'Bayside', 827),
  ('Canton', true, 'OH', 'Waywood', 828),
  ('Salt Lake City', true, 'UT', 'Gateway', 829),
  ('Knoxville', true, 'TN', 'Darwin', 830),
  ('Paterson', false, 'NJ', 'Scott', 831),
  ('Tulsa', false, 'OK', 'Hazelcrest', 832),
  ('Fort Lauderdale', false, 'FL', 'Trailsway', 833),
  ('Atlanta', false, 'GA', 'Southridge', 834),
  ('Sioux Falls', false, 'SD', 'Shoshone', 835),
  ('Fresno', false, 'CA', 'Oneill', 836),
  ('Staten Island', true, 'NY', 'Steensland', 837),
  ('Norfolk', false, 'VA', 'Talisman', 838),
  ('South Bend', true, 'IN', 'Alpine', 839),
  ('New Haven', false, 'CT', 'South', 840),
  ('Cincinnati', true, 'OH', 'Luster', 841),
  ('Akron', true, 'OH', 'Fairfield', 842),
  ('Boise', false, 'ID', 'Sherman', 843),
  ('Omaha', false, 'NE', 'Manufacturers', 844),
  ('Kansas City', false, 'MO', 'Eastlawn', 845),
  ('Wichita', false, 'KS', 'Corscot', 846),
  ('Crawfordsville', true, 'IN', 'Park Meadow', 847),
  ('Kansas City', true, 'MO', 'Harper', 848),
  ('Baltimore', false, 'MD', 'Waubesa', 849),
  ('College Station', false, 'TX', 'Calypso', 850),
  ('Richmond', true, 'VA', 'Mendota', 851),
  ('Portland', false, 'OR', 'Carey', 852),
  ('Shawnee Mission', false, 'KS', 'Pankratz', 853),
  ('Helena', true, 'MT', 'Carey', 854),
  ('El Paso', false, 'TX', 'Oakridge', 855),
  ('Chicago', true, 'IL', 'Memorial', 856),
  ('Houston', false, 'TX', 'Mifflin', 857),
  ('Minneapolis', false, 'MN', 'Sage', 858),
  ('Los Angeles', true, 'CA', 'Becker', 859),
  ('Riverside', true, 'CA', 'Leroy', 860),
  ('San Francisco', false, 'CA', 'Westerfield', 861),
  ('Racine', true, 'WI', 'Bluestem', 862),
  ('Phoenix', true, 'AZ', 'Jay', 863),
  ('Waltham', true, 'MA', 'Knutson', 864),
  ('Wichita', true, 'KS', '7th', 865),
  ('Washington', true, 'DC', 'Union', 866),
  ('Tulsa', false, 'OK', 'Vermont', 867),
  ('Philadelphia', false, 'PA', 'Morrow', 868),
  ('Spokane', true, 'WA', 'Sage', 869),
  ('Berkeley', false, 'CA', 'Dryden', 870),
  ('Austin', false, 'TX', 'Sycamore', 871),
  ('Colorado Springs', false, 'CO', 'Talisman', 872),
  ('Evansville', true, 'IN', 'East', 873),
  ('Erie', true, 'PA', 'Browning', 874),
  ('Erie', false, 'PA', 'Manley', 875),
  ('Chandler', true, 'AZ', 'Center', 876),
  ('Albany', false, 'NY', 'Erie', 877),
  ('Vancouver', true, 'WA', 'Twin Pines', 878),
  ('Whittier', false, 'CA', 'Moulton', 879),
  ('Corpus Christi', true, 'TX', 'Mccormick', 880),
  ('Winston Salem', false, 'NC', 'Ridgeview', 881),
  ('Portland', true, 'OR', 'Shopko', 882),
  ('Olympia', true, 'WA', 'Magdeline', 883),
  ('Santa Ana', false, 'CA', 'Mcguire', 884),
  ('Shreveport', true, 'LA', 'Straubel', 885),
  ('Wichita', true, 'KS', 'Anzinger', 886),
  ('Trenton', false, 'NJ', 'Fair Oaks', 887),
  ('Washington', false, 'DC', 'Eastwood', 888),
  ('Paterson', false, 'NJ', 'Tennessee', 889),
  ('Fort Worth', true, 'TX', 'Mesta', 890),
  ('Anderson', false, 'SC', 'Homewood', 891),
  ('Dallas', true, 'TX', 'Lighthouse Bay', 892),
  ('Bradenton', true, 'FL', 'Coolidge', 893),
  ('Portland', false, 'ME', '2nd', 894),
  ('Clearwater', true, 'FL', 'Grasskamp', 895),
  ('Lima', true, 'OH', 'Petterle', 896),
  ('North Hollywood', false, 'CA', 'Melrose', 897),
  ('Albany', false, 'NY', 'Fairfield', 898),
  ('San Antonio', true, 'TX', 'Memorial', 899),
  ('Burbank', true, 'CA', 'Monterey', 900),
  ('Las Vegas', true, 'NV', 'Hoffman', 901),
  ('Albuquerque', true, 'NM', 'Blue Bill Park', 902),
  ('Flushing', false, 'NY', 'Union', 903),
  ('Fort Lauderdale', false, 'FL', 'Vidon', 904),
  ('Lincoln', true, 'NE', 'Schmedeman', 905),
  ('Riverside', true, 'CA', 'Gerald', 906),
  ('Suffolk', false, 'VA', 'Blackbird', 907),
  ('Indianapolis', false, 'IN', 'Almo', 908),
  ('Cincinnati', false, 'OH', 'New Castle', 909),
  ('Simi Valley', false, 'CA', 'Upham', 910),
  ('Garland', true, 'TX', 'Victoria', 911),
  ('New York City', true, 'NY', 'Bashford', 912),
  ('Toledo', true, 'OH', 'Florence', 913),
  ('Charlotte', true, 'NC', 'Butterfield', 914),
  ('Reading', false, 'PA', 'Hoffman', 915),
  ('Washington', false, 'DC', 'Surrey', 916),
  ('North Las Vegas', false, 'NV', 'Derek', 917),
  ('Lubbock', true, 'TX', 'Elka', 918),
  ('Corpus Christi', false, 'TX', 'Lighthouse Bay', 919),
  ('Pittsburgh', false, 'PA', 'Dawn', 920),
  ('Honolulu', false, 'HI', 'Weeping Birch', 921),
  ('Saint Paul', false, 'MN', 'Esker', 922),
  ('Lehigh Acres', true, 'FL', 'Laurel', 923),
  ('Savannah', false, 'GA', 'Amoth', 924),
  ('Washington', false, 'DC', 'Northview', 925),
  ('Boston', true, 'MA', 'Dunning', 926),
  ('Baton Rouge', true, 'LA', 'Pine View', 927),
  ('Jacksonville', true, 'FL', '3rd', 928),
  ('New Castle', false, 'PA', 'Sunfield', 929),
  ('Madison', false, 'WI', 'Schlimgen', 930),
  ('Los Angeles', true, 'CA', 'Elmside', 931),
  ('Minneapolis', true, 'MN', '2nd', 932),
  ('Atlanta', false, 'GA', 'Moland', 933),
  ('Columbus', false, 'MS', 'Fairfield', 934),
  ('Kissimmee', false, 'FL', 'Fordem', 935),
  ('Youngstown', false, 'OH', 'Clove', 936),
  ('Baton Rouge', false, 'LA', 'Bonner', 937),
  ('Peoria', false, 'IL', 'Novick', 938),
  ('Harrisburg', false, 'PA', 'Longview', 939),
  ('Phoenix', true, 'AZ', 'Mandrake', 940),
  ('Austin', false, 'TX', 'Northwestern', 941),
  ('Fort Wayne', false, 'IN', 'Ridgeway', 942),
  ('Atlanta', false, 'GA', 'Loomis', 943),
  ('Lubbock', true, 'TX', 'Moland', 944),
  ('Anniston', false, 'AL', 'Cambridge', 945),
  ('Long Beach', true, 'CA', 'Roxbury', 946),
  ('Providence', true, 'RI', 'Porter', 947),
  ('Roanoke', false, 'VA', 'Thackeray', 948),
  ('Cedar Rapids', false, 'IA', 'Redwing', 949),
  ('Las Vegas', true, 'NV', 'Sunfield', 950),
  ('Seattle', false, 'WA', 'Jackson', 951),
  ('Reno', false, 'NV', 'Weeping Birch', 952),
  ('Baltimore', true, 'MD', 'Swallow', 953),
  ('South Bend', false, 'IN', 'Cambridge', 954),
  ('Anchorage', false, 'AK', 'Lakewood Gardens', 955),
  ('Albany', true, 'NY', 'Golf', 956),
  ('Modesto', false, 'CA', 'Hallows', 957),
  ('Philadelphia', false, 'PA', 'Dovetail', 958),
  ('Las Vegas', true, 'NV', 'Grover', 959),
  ('Duluth', true, 'GA', 'Lakeland', 960),
  ('Omaha', false, 'NE', 'Washington', 961),
  ('Irvine', true, 'CA', 'Center', 962),
  ('Tulsa', false, 'OK', 'Huxley', 963),
  ('Nashville', false, 'TN', 'Arapahoe', 964),
  ('Fort Myers', false, 'FL', 'Stuart', 965),
  ('Trenton', true, 'NJ', 'Merchant', 966),
  ('Amarillo', true, 'TX', 'Petterle', 967),
  ('West Hartford', false, 'CT', 'Grim', 968),
  ('Oklahoma City', true, 'OK', 'Onsgard', 969),
  ('Washington', false, 'DC', 'Eastwood', 970),
  ('Arlington', true, 'VA', 'Westend', 971),
  ('Pittsburgh', false, 'PA', 'Monica', 972),
  ('Miami', true, 'FL', 'Prairie Rose', 973),
  ('Baltimore', true, 'MD', 'Reinke', 974),
  ('Buffalo', false, 'NY', 'Talisman', 975),
  ('Sioux Falls', true, 'SD', 'Hintze', 976),
  ('Philadelphia', true, 'PA', 'Carpenter', 977),
  ('Cedar Rapids', false, 'IA', 'Boyd', 978),
  ('Alexandria', false, 'LA', 'Lien', 979),
  ('Santa Barbara', false, 'CA', 'Monterey', 980),
  ('El Paso', false, 'TX', 'Forest', 981),
  ('Rochester', true, 'NY', 'Killdeer', 982),
  ('Portland', true, 'OR', 'Tony', 983),
  ('Springfield', false, 'IL', 'Gina', 984),
  ('Roanoke', false, 'VA', 'Veith', 985),
  ('Grand Rapids', true, 'MI', 'Oak Valley', 986),
  ('New Orleans', true, 'LA', 'Oakridge', 987),
  ('Boston', false, 'MA', 'Dunning', 988),
  ('Merrifield', true, 'VA', 'Melody', 989),
  ('Phoenix', false, 'AZ', 'School', 990),
  ('Nashville', false, 'TN', 'Calypso', 991),
  ('Fresno', false, 'CA', 'Old Gate', 992),
  ('Houston', false, 'TX', 'Vera', 993),
  ('Syracuse', false, 'NY', 'Buhler', 994),
  ('Los Angeles', false, 'CA', 'Vera', 995),
  ('Richmond', true, 'VA', '3rd', 996),
  ('Salt Lake City', true, 'UT', 'Starling', 997),
  ('Philadelphia', true, 'PA', 'Eastlawn', 998),
  ('Las Vegas', false, 'NV', 'Sunnyside', 999),
  ('New York City', true, 'NY', 'Fordem', 1000)
